cmake_minimum_required(VERSION 3.16)
project(hangeul_effort_limit)
find_package(ament_cmake REQUIRED)
find_package(gz_sim_vendor REQUIRED)
find_package(gz-sim8 REQUIRED)
find_package(gz_ros2_control REQUIRED)
find_package(pluginlib REQUIRED)
find_package(hardware_interface REQUIRED)
add_library(hangeul_effort_limit SHARED src/effort_limit.cpp)
target_compile_features(hangeul_effort_limit PUBLIC cxx_std_17)
ament_target_dependencies(hangeul_effort_limit gz_ros2_control pluginlib hardware_interface)
pluginlib_export_plugin_description_file(gz_ros2_control plugins.xml)
install(TARGETS hangeul_effort_limit LIBRARY DESTINATION lib)
ament_package()
